clusterGroup:
  name: hub
  isHubCluster: true
  namespaces:
    - kuadrant-system
    - istio-system
    - vault
    - open-cluster-management 
    - golang-external-secrets
    - api-gateway

  subscriptions:
    acm:
      name: advanced-cluster-management
      namespace: open-cluster-management
      channel: release-2.10
      #csv: advanced-cluster-management.v2.6.1

    sailoperator:
      name: sailoperator
      namespace: openshift-operators
      source: community-operators
      channel: 3.0-dp1

    kuadrant-operator:
      name: kuadrant-operator
      namespace: openshift-operators
      source: community-operators
      channel: stable

  projects:
    - hub

  # This kind of variable substitution will work with any of the variables the Validated Patterns operator knows
  # about and sets, so this is also possible, for example:
  #   - '/overrides/values-{{ $.Values.global.hubClusterDomain }}.yaml'
  #   - '/overrides/values-{{ $.Values.global.localClusterDomain }}.yaml'
  applications:
    acm:
      name: acm
      namespace: open-cluster-management
      project: hub
      path: common/acm
      ignoreDifferences:
        - group: internal.open-cluster-management.io
          kind: ManagedClusterInfo
          jsonPointers:
            - /spec/loggingCA
    vault:
      name: vault
      namespace: vault
      project: hub
      path: common/hashicorp-vault

    golang-external-secrets:
      name: golang-external-secrets
      namespace: golang-external-secrets
      project: hub
      path: common/golang-external-secrets

    # specific configuration helm charts for our rhcl demo
    istio-sail-op:
      name: istio-sail-op
      namespace: istio-system
      project: hub
      path: charts/deloitte/istio-config

    catalog-source:
      name: catalog-source
      namespace: kuadrant-system
      project: hub
      path: charts/deloitte/catalog-source-config

    initial-setup:
      name: initial-setup
      namespace: kuadrant-system
      project: hub
      path: charts/deloitte/initial-setup

    secure-connect:
      name: secure-connect
      namespace: kuadrant-system
      project: hub
      path: charts/deloitte/secure-connect

  imperative: {}
  managedClusterGroups:
    development:
      name: development
      acmlabels:
        - name: clusterGroup
          value: rhcl-development
      helmOverrides:
        - name: clusterGroup.isHubCluster
          value: false
    exampleRegion:
      name: group-one
      acmlabels:
        - name: clusterGroup
          value: rhcl-demo
      helmOverrides:
        - name: clusterGroup.isHubCluster
          value: false
