---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: {{ .Values.secure.config.gatewayName }} 
  namespace: {{ .Values.secure.config.namespace }} 
  labels:
    kuadrant.io/gateway: "true"
spec:
    gatewayClassName: istio
    listeners:

    - allowedRoutes:
        namespaces:
          from: All
      hostname: "*.{{ .Values.secure.config.rootDomainId }}" 
      name: api
      port: 443
      protocol: HTTPS
      tls:
        certificateRefs:
        - group: ""
          kind: Secret
          name: api-${GATEWAY_NAME}-tls
        mode: Terminate
